version: 1.0.{build}

install:
  - ps: wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-win32-x86.zip -OutFile cmake.zip
  - cmd: echo "Unzipping cmake..."
  - cmd: 7z x cmake.zip -o"C:\Program Files (x86)\" -y > nul
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\Program Files (x86)\cmake-3.0.2-win32-x86\bin
  - cmd: cmake --version
  - cmd: echo "Downloading biicode..."
  - ps: wget http://www.biicode.com/downloads/latest/win -OutFile bii-win.exe
  - cmd: bii-win.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii
  - cmd: bii -v
  - cmd: del bii-win.exe
  - cmd: del cmake.zip
  - cmd: echo "Download submodules..."
  #- cmd: git submodule update --init --recursive

before_build:
  - cmd: bii init %project_name%
  - cmd: cd %project_name%
  - cmd: bii new %block_user%/%block_name%
  # copy files and folders
  #- cmd: xcopy "%APPVEYOR_BUILD_FOLDER%" blocks\%block_user%\%block_name%\ /e
  - cmd: for %%i in (../*) do if %%i NEQ "%project_name%" move "..\%%i" blocks\%block_user%\%block_name%\
  - cmd: for /d %%i in (../*) do if %%i NEQ "%project_name%" move "..\%%i" blocks\%block_user%\%block_name%\
  - cmd: bii cpp:configure -G "Visual Studio 10"

build_script:
  - cmd: bii cpp:build

test_script:
  - cmd: cd bin
  #- cmd: jgsogo_xml_parser_examples_xml_parser_basic_main.exe


deploy_script:
  - cmd: bii user %block_user% -p %secured_passwd%
  - if defined APPVEYOR_REPO_TAG_NAME set VERSION=%APPVEYOR_REPO_TAG_NAME%  
  - if defined APPVEYOR_REPO_TAG_NAME bii publish --tag=%tag% --versiontag=%VERSION% || dir
  - if not defined APPVEYOR_REPO_TAG_NAME bii publish --tag=%dev_tag% || dir

  
on_success:
  - cmd: cd /%project_name%/blocks/%block_user%/%block_name%
  - ps: |    
        $new_biiconf = get-content biicode.conf
        $orig_biiconf = get-content "$env:APPVEYOR_BUILD_FOLDER\biicode.conf"     
        if (diff $new_biiconf $orig_biiconf){
           'different, updating biicode parents'
           git checkout "$env:APPVEYOR_REPO_BRANCH"
           git config --global core.autocrlf true
           git config --global credential.helper store 
           Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
           git remote add neworigin "$env:github_repo"
           git config --global user.email "$env:github_email"
           git config --global user.name "$env:github_user"
           git add .
           git commit -m "Updated biicode parents [skip ci]"
           git push neworigin "$env:APPVEYOR_REPO_BRANCH"
           }Write-Host "Updated biicode parents" else {
            'equal, no parents update needed'
          }
          

environment:
  project_name:
    "jgsogo_expat"
  block_user:
    "jgsogo"
  block_name:
    "expat"
  secured_passwd:
    secure: Uu7M7OBkfYV3lIvqwceP4g==
  access_token:
    secure: 0hXDOpyLRXuTWG+pZXe0i/NftkT+J6niFDFKU59BgE2h3Din2+i8biFdgVVc1l2b
  tag:
    "STABLE"
  dev_tag:
    "DEV"
  github_user:
    "jgsogo"
  github_email:
    "jgsogo@gmail.com"
  github_repo:
    "git@github.com:jgsogo/expat.git"
